### ISSUE TITLE
PlaybackCompleted event gets fired when video is paused

### ISSUE THREAD

**Issue by pssp-sven** [SuRGeoNix/Flyleaf#120]
Hi @SuRGeoNix,
is this really on purpose? Previously this event was only fired when the video reached the end (playing forward) or when it got to start again (playing backwards). Frankly I would expect it to work this way.

**Comment by pssp-sven** [comment]
To test if the video reached the end, I'll check if Player.Status == Status.Ended. That way it works, but It's still not that intuitive.

**Comment by SuRGeoNix** [comment]
HI @pssp-sven, yes OnPlaybackCompleted changed so it will fire every time that screamer completes (forgot to add it on breaking changes!). You can identify the reason by checking the Status and Error. I don't understand what is the issue here? What do you mean intuitive? What exactly do you want to identify? Possible if Status != Status.Paused then you can identify that it stopped unexpectedly or ended properly?

**Comment by pssp-sven** [comment]
I use a switch statement to react on the different states now. That's ok and even more flexible than before.
Maybe PlaybackCompleted is not the best name anymore, because intuitively I would expect it to fire at the very end. But it's not that important.

**Comment by SuRGeoNix** [comment]
Yes, I get your point now. I thought that the Status would be enough from the beginning but you ask for additional events. Maybe I should rename it, or put it back as it was before. Let me know what you think and I will this on the next update.
