### ISSUE TITLE
[Feature Request] Don't dispose the last frame and clear the screen on new input

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#122]
Use latest nuget version.
Now open a video first and then open another video, it will be black for a while in the middle.Maybe it is not a good experience.

**Comment by SuRGeoNix** [comment]
Switching between videos works fine and fast. I don't understand what is the black in the middle. The only black that I see is the clear screen (with black) when a video stops.  Does this happens on sample version?

**Comment by swimfish09** [comment]
Yes, it is the clear screen(with black).If switching between live streams, the black will keep for some time.

**Comment by SuRGeoNix** [comment]
@swimfish09 Please try to explain better what the issue is, or what the feature request is. I still can't understand if it is a bug or a request. So you say that only when you open a network stream (which requires some time to buffer), when you wait for it to open/buffer you will see black instead of the last frame of the previous opened stream? So you would prefer to keep that frame when you open another stream?

**Comment by swimfish09** [comment]
Yes I would prefer to keep that frame the last frame of the previous opened stream when i open another stream.
