### ISSUE TITLE
Win11 set  config.Video.VideoProcessor  to Flyleaf, video brightness is dim

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#132]
use latest master code.
Now, I want to support pan and zoom,I set config.Video.VideoProcessor  to Flyleaf, video brightness is dim.

**Comment by swimfish09** [comment]
Hi @swimfish09 , I have tried the latest master code, the problem seems not disappeared.

**Comment by SuRGeoNix** [comment]
@swimfish09 Does the sample version work for that?

**Comment by swimfish09** [comment]
Actually I have tried the the sample version. The sample version does work for that.

**Comment by SuRGeoNix** [comment]
Probably this is not related to Win11 but with the GPU filters and values. You will need to debug the Config.Video.Filters and help me finger out what is going wrong.

**Comment by swimfish09** [comment]
After pan and zoom  method UpdateVideoProcessor was not triggered，then If I change VideoProcessor to Flyleaf, because of 
Config.Video.VideoProcessor == videoProcessor  Config.Video.Filters was not reseted.

**Comment by SuRGeoNix** [comment]
You don't help me much with this information. Are you talking about your app or the sample version?
Because I can see in sample version that UpdateVideoProcessor will be called on pan/zoom.
Try the following set Config.Video.VideoProcessor to D3D11 before you set it to Flyleaf (to ensure UpdateVideoProcessor will be called). Try also to do whatever you are doing after opening the input not before.

**Comment by swimfish09** [comment]
the sample version

**Comment by SuRGeoNix** [comment]
I will re-close this as if you can't help me understand the issue I can't fix it, sorry
