### ISSUE TITLE
Current Time when Video Stops

### ISSUE THREAD

**Issue by Jacques-eMediaIT** [SuRGeoNix/Flyleaf#138]
I've noticed that the current time doesn't reach the end when a video stops playing. Minor issue, but would be nice if it matched up with the duration. It would probably not be noticeable with longer videos.

The values in the bottom right are the ticks for current and duration.

![image](https://user-images.githubusercontent.com/84329887/162768624-461bc641-206f-4248-bf46-42715f202660.png)

**Comment by SuRGeoNix** [comment]
Well, I have came across this one in the past. There is a reason that happens on some cases and cannot really be fixed as I remember. When Flyleaf plays a video (which has also audio) it focuses on the video stream. So if the audio has 10 seconds before and 10 seconds at the end without a video, Flyleaf will skip both of them. With this logic it will never have issues with network streams in case of wrong packets/timestamps.

If you check the log for the above sample video you will see the following:-

```
[Format  ] QuickTime / MOV/mov,mp4,m4a,3gp,3g2,mj2 | mov,mp4,m4a,3gp,3g2,mj2,psp,m4b,ism,ismv,isma,f4v | 00:00:00/00:00:05.3120000 | 00:00:00/00:00:05.3120000
[Video #0] h264 yuv420p 1280x720 @ 25 | [Color: BT709] [BR: 1205959] | 00:00:00/00:00:05.2800000 | 00:00:00/00:00:05.2800000
[Audio #1-eng] aac fltp@16 48KHz 5.1 | [BR: 384828] | 00:00:00/00:00:05.3119999 | 00:00:00/00:00:05.3119999
```
The duration of the audio is longer than the video. This could also happen because of a missing or broken drain video packet.
