### ISSUE TITLE
FlyleafHost.Wpf: Owner Window Loses Focus (Surface & Overlay)

### ISSUE THREAD

**Issue by JacquesDoubell** [SuRGeoNix/Flyleaf#257]
The main / host window loses focus when clicking on the player area.

The behaviour can be seen in FlyleafPlayer (Custom - MVVM) (WPF). I've tried isFocusable = false on several elements.

It seems to have changed with the breaking changes introduced around 9 Nov 22 when VideoView was renamed to FlyLeafHost. The old version with VideoView gave focus to the main app window when clicking on the video. It would be nice to have the old behaviour back if possible.

**Comment by SuRGeoNix** [comment]
Hi @JacquesDoubell, from v3.6 that have been a lot of changes for the FlyleafHost (old VideoView) and I will review this in the next update as I think you are right (focus should stay at the host)

**Comment by JacquesDoubell** [comment]
Thank you :)

btw, I see FFmpeg v6 has been released recently.

**Comment by SuRGeoNix** [comment]
@JacquesDoubell, yes but FFmpeg.Autogen didn't update to v6 yet

Just check this in depth, at v3.5 it was indeed working, however it had the same issue for the overlay (probably because old winformshost was using a 'hack' with win forms but now i'm using a WPF window). I will need to review this more as I was thinking to create a custom window for the surface at least to ensure even better performance. 

Found some related links here

1) https://stackoverflow.com/questions/2877159/is-it-possible-to-create-a-sub-window-which-will-not-deactivate-the-parent
2) https://web.archive.org/web/20100612183744/http://www.catch22.net/tuts/docking1

**Comment by SuRGeoNix** [comment]
@JacquesDoubell You can now update your App's FFmpeg.Autogen NuGet to v6 and link to FFmpeg v6 libs. From my testing works fine already without any changes in FlyleafLib. However, I still didn't patch v6 for the HLS live seeking issue.
