### ISSUE TITLE
Unable to use MouseDown="Window_MouseDown"

### ISSUE THREAD

**Issue by shushu789** [SuRGeoNix/Flyleaf#276]
My project uses WPF MVVM, I want to add a mouse down event to the form, but I found it doesn't work, another event (SizeChanged="Window_SizeChanged") is normal. Here is the main code snippet:
## MainWindow.xaml
`<window
...
MouseDown="Window_MouseDown">
<Border>
     <fl:FlyleafHost Player="{Binding Player}" KeyBindings="Surface" Cursor="Hand">
    ...
</Border>
</window>
`
## MainWindow.xaml.cs
No matter how I debug it, it doesn't enter this method
`private void Window_MouseDown(object sender, MouseButtonEventArgs e)
        {
            Debug.WriteLine("MouseDown..");
        }
`
Also I tested "FlyleafPlayer (WPF Control) (WPF)" in sample project and it works. But in "FlyleafPlayer (Custom - MVVM) (WPF)" same as me above, doesn't work. Is it because of using FlyleafME? Can you give me some inspiration to solve it, thanks a lot

**Comment by SuRGeoNix** [comment]
@shushu789 check https://github.com/SuRGeoNix/Flyleaf/wiki/FlyleafHost

In WPF, there are two new windows for each flyleafhost control the Surface and the Overlay window. So you need to listen to those windows events. In the main sample it works because it is a stand alone window flyleafhost (the surface and the main window is the same) but you can't draw anything else in the main window only in the overlay.

Let me know if you need more help.
