### ISSUE TITLE
All audio frames dropped by Flyleaf, But it can play well with ffplay.

### ISSUE THREAD

**Issue by swimfish09** [SuRGeoNix/Flyleaf#295]
use lastest master code.
the log as bellow
[18400-player-2023-05-08.log](https://github.com/SuRGeoNix/Flyleaf/files/11421276/18400-player-2023-05-08.log)

**Comment by SuRGeoNix** [comment]
@swimfish09 Is it possible to send a sample media to reproduce it? If not can you confirm that by commenting this 'if' https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/MediaPlayer/Audio.cs#L280 will play the audio properly and synced?

**Comment by swimfish09** [comment]
@SuRGeoNix I have sent you with a sample media.

**Comment by SuRGeoNix** [comment]
@swimfish09 This is a really bad audio codec and mux. You can make it work by enabling the Config.Audio.FiltersEnabled audio filters (now are stable enough to use them). However, this has small packages with 2ms for each audio frame, I've even noticed sending the same timestamps from time to time (which audio filters can fix). From the other hand instead of 2 ms audio filters add 20 ms duration which probably means that you loose audio/video sync? Another issue is that to properly sync 2ms each time the main thread (screamer) will not sleep at all which is bad for performance. I will try to fix this in the future but for now use audio filters and ideally change the codec / parameters in the source.

**Comment by swimfish09** [comment]
Hi @SuRGeoNix , The camera device can not change the codec / parameters. Actually audio/video sync is not necessary  in video surveillance scenarios .We should ensure that the video and audio can be played.

**Comment by swimfish09** [comment]
how to adding the duration each time?

**Comment by SuRGeoNix** [comment]
@swimfish09 I was talking about the library's design not your applications. Just enable Config.Audio.FiltersEnabled and re-open this if you still have issues.
