### ISSUE TITLE
Overriding output frame rate

### ISSUE THREAD

**Issue by benwilkinson** [SuRGeoNix/Flyleaf#323]
It appears that the playback frame rate of the video is fixed at the rate of the input video. 

I was playing 1fps video with a timestamp, it plays back ticking 1s at a time, I increased the Speed to 10x and on the video I'm seeing it skip 10s at a time. 

At the same time if I'm playing 30fps video I would like to be able to lower the playback frame rate so that when I'm playing many streams at high Speed it doesn't completely consume all resources.

Is there an easy way to override the frame rate of playback?

This is in WPF if that makes a difference.

**Comment by SuRGeoNix** [comment]
Hi @benwilkinson, when you increase the speed in flyleaf it will try to drop some frames so the fps it will not be very high to keep the GPU low if possible. In case of 1fps video this can be visible indeed, I will consider adding a config for that to enable/disable it.

So did you try to reduce the speed of 30 fps video to achieve a lower frame rate? What was the issue here?

Generally changing the fps means changing the speed. The issue with high resources comes when you increase the speed. What you cannot avoid is decoding of all the (IPB) frames (even those that you don't care to render) and decoding process is heavier than rendering (except if you have raw data that are not require any decoding).

If you want to do a custom manipulation of the rendering you could make your own 'Screamer'.

**Comment by benwilkinson** [comment]
@SuRGeoNix Sorry for the delay. The performance is great! That and the active development you're doing on this library is why we're interested in using it. I'm currently using ffme, but your library has many attractive features, there are just a couple roadblocks preventing the switch.

Dropping frames for performance makes sense to me. My issues are around having video that can range from 1fps to 30fps (majority is 5-10fps), when I playback 1fps video at 10x I am still only getting 1fps output, so the image jumps 10s at a time. 

In other cases I'm playing up to 8 cameras synced up and if they are 30fps videos and are all trying to maintain 30fps at high speed it leads to poor playback in some of the players. If I understand what you're saying correctly, this is because it's still decoding every frame? So at 10x is has to decode 300fps even if it only renders at 30fps?

**Comment by benwilkinson** [comment]
@SuRGeoNix that makes sense, keyframes and then just diffs in between. Would it be possible to drop whole sections of keyframes when the playback speed is high? 

If there is a config we can set to max out the rendered frame rate. Say we set it to 30fps, and turn the speed up to 10x.
I have video with key frames durations of 0.2-0.4s (average 0.24s, I don't quite understand why for 5fps video)

So if we were decoding every frame that would be 50fps decoded (40 key fps). Could we not skip decoding many of those key frames? Again I lack a lot of knowledge about the intricacies of decoding video so I'm willing to bet I'm making incorrect assumptions.

**Comment by benwilkinson** [comment]
I just found another problem with it as well while integrating it into our software. In specific circumstances it skips all frames. I've committed a fix for this.

I tried out what you were suggesting, adding a flag to not frames at increased speed. It definitely increases the load on the GPU
10fps video, 6 players, 12x speed
Drop frames: 15% gpu
Don't drop: 40% gpu

My use case is for up to 8 players at up to 16x speed (more likely 4 players 4-8x speed). Generally video recorded at 5fps, though there are some cases at 30fps.

If this isn't the correct place to drop frames then why is the decoder dropping Speed-1 frames?
