### ISSUE TITLE
Sound cracling / popping when seeking

### ISSUE THREAD

**Issue by MrJacquers** [SuRGeoNix/Flyleaf#351]
I've been using the on the old version of the library (3.5.10) in my project and I'm busy upgrading it to use the latest version. I've noticed an increase in the popping / crackling sound when seeking in some videos. The specific video was downloaded from YouTube with yt-dlp. It's especially noticeable at the start of the video or when seeking back to the start.

PotPlayer has a little bit of crackling and VLC seems to have none.

Not a big issue, but would be nice to minimize this :)

Examples below.

https://github.com/SuRGeoNix/Flyleaf/assets/84329887/df1bbeb9-9514-46a9-837f-b5d9062d2602

https://github.com/SuRGeoNix/Flyleaf/assets/84329887/541a11d3-8771-455b-ad95-7e21ac66bd8a

**Comment by SuRGeoNix** [comment]
@MrJacquers First of all, congrats watching Nick, he is awesome :)

I think this issue still exists with the latest version, I tried to fix it once but I couldn't. I was not sure if the issue was the XAudio or my code. Probably, is my code, I'm guessing the circular audio buffer with the pointers that passes to XAudio. I will give another try to fix it at the next update.

**Comment by MrJacquers** [comment]
Cool, thanks :)

**Comment by SuRGeoNix** [comment]
Not easy to spot again, but it seems is related with the sample rate. I cannot easily reproduce it when the audio stream is embedded to the main demuxer/format. Can you confirm that this is not happening with 48Khz sample rates? (You can make it easier happened with pause/play rather than seek). If that's the case I will need to convert any input sample rate to 48Khz instead of leaving it as is.

**Comment by MrJacquers** [comment]
Hope this debug info helps. It also happens with play / pause, like you've said.

![image](https://github.com/SuRGeoNix/Flyleaf/assets/84329887/fd3d4ec9-d1b1-4286-8eda-ceedd81a550b)

Found this post, which you may have seen as well. https://stackoverflow.com/questions/46831684/xaudio2-cracking-output-when-using-a-dynamic-buffer

Sounds complicated :)

**Comment by MrJacquers** [comment]
btw, the file is saved to my hdd, I'm not streaming it.

**Comment by SuRGeoNix** [comment]
Yes, I've seen that stackoverflow question, however I'm not touching the data (pointers) that already in used. I used the downloader for the same video and while I had some crackling when used directly from the player that didn't happen from the saved file (48Khz). Which means that is related somehow with the external streams and sample rates.

**Comment by SuRGeoNix** [comment]
I had another way to avoid this issue in the past but when I was trying to fix the audio sync to be as accurate as possible I forgot to keep this think in mind. It should be fixed now without affecting the video/audio sync.

**Comment by MrJacquers** [comment]
Thank you :)

**Comment by SuRGeoNix** [comment]
No problem, thanks for reminding me this, as audio is much better now :)
