### ISSUE TITLE
drag and drop

### ISSUE THREAD

**Issue by zer0ne1** [SuRGeoNix/Flyleaf#356]
i can get flyleafHost drop when i use event drop.
but i cannot get flyleafHost drag start.
Help me pls!
Many thanks!

**Comment by SuRGeoNix** [comment]
Hi @zer0ne1, what are you trying to do exactly and which one do you use (winforms/wpf/winui3?). Did you try the embedded Drag&Drop functionality?

**Comment by zer0ne1** [comment]
i'm using wpf. i used events DragEnter, DragOver, DragLeaver but no event gets the flyleafhost drag start

**Comment by SuRGeoNix** [comment]
First you need to understand how the FlyeaflHost works for WPF. It's not just a UserControl but it also has a Surface and an Overlay (only if you have overlay content) windows. So, will need to listen to the events on the Windows instead of the UserControl. eg:-

```csharp
flyleafHost1.Surface.Drop += (o, e) => { ... };
```

However, from a quick look [here](https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib/Controls/WPF/FlyleafHost.cs#L1041) I see that I use a private class for the swap data. I could add a static event on FlyleafHost that will inform for the two players that are swapping.

**Comment by zer0ne1** [comment]
Thanks but I mean I do put a grid on the surface of flyleafhost. When dragged and dropped, the grids do not swap.

https://github.com/SuRGeoNix/Flyleaf/assets/71746399/602a9561-c8c8-40d9-b746-1c11f5da270a

**Comment by SuRGeoNix** [comment]
The embedded swap functionality is for the Players not for the Overlay Content. You can do this yourself (check when the Player property is changing, if that not works let me know if you need a static event that I've mentioned).

**Comment by zer0ne1** [comment]
I know, so I use the drop event to get the droped host information, however I can't know which host is being draged. Do you have any way to help me?

**Comment by SuRGeoNix** [comment]
You could just use the Player property for bindings so it would automatically update after the swap with the new values. Not sure what you want to do. I will close this, but free to ask for an event if that's that you actually need.
