### ISSUE TITLE
considering an arm64 build

### ISSUE THREAD

**Issue by nekoteai** [SuRGeoNix/Flyleaf#369]
good project if you can support windows arm64 arch,thank you

**Comment by SuRGeoNix** [comment]
Thanks @nekoteai, I will try to include it in v4 (closing it as duplicate to #216)

**Comment by eliacanavera1111** [comment]
Hi @SuRGeoNix, are you still working on support for arm64? do you plan to release it for net framework 4.8 too?

**Comment by eliacanavera1111** [comment]
@SuRGeoNix

**Comment by SuRGeoNix** [comment]
Hi @eliacanavera1111, Flyleaf will support whatever is supported from both .NET and FFmpeg.
.NET Framework will not supported anymore.

**Comment by eliacanavera1111** [comment]
Thanks @SuRGeoNix for reply, so will support arm64 in the future but only on .NET, ok. Another thing...

today on arm64 devices after couple hours of activity the program with flyleaf crashes throwing "UCEERR_RENDERTHREADFAILURE" error, and this never happens on intel devices also after days of activity, and never happens also on arm64 if instead of flyleaf I use a media player with arm64 support, so it's probably because performance of the emulator for apps not compatible with arm64.

It's really crucial in my application that the program runs without interruptions and also the compatibility with arm64 devices.
For now that there isn't an arm64 release, can you suggest me a possible magic workaround to try?

**Comment by SuRGeoNix** [comment]
@eliacanavera1111 This seems more like a Wpf issue. I guess you are talking about Wpf FlyleafHost? It has a lot of customization to act as a 'swapchain' control which might arm64 for some reason does not like it. I would bet that WinUI3 wouldn't crash.

That will not be easy for me to debug it at least for now.
