### ISSUE TITLE
Open/OpenAsync with ClearScreenOnOpen still shows black frame 

### ISSUE THREAD

**Issue by jeroenm2** [SuRGeoNix/Flyleaf#442]
Hi, as others have tried, I am trying to play video's and images without a black frame between them. I am using FlyleafLib.Controls.WPF 1.3.7. I did set the property ClearScreenOnOpen to true (a little confusing).

I do the following:

- Play a video file
- Register a callback on Player.OpenCompleted
- Call Player.OpenAsync
- In the Callback of OpenCompleted I do a play, but on start of the callback the mediaplayer is alread black.

The same counts for images, especially if the images are white, the black flashes are very clear.

It does seem like ClearScreenOnOpen is not functioning properly, if not, can you provide me instructions on how to achieve this?
Very happy with your library BTW

**Comment by SuRGeoNix** [comment]
@jeroenm2 You are right, that was there from old days probably not working at all now. I will try to fix that, the issue is that when you stop/close the input it will destroy the swap chain and all the frames (including the last visible frame) to ensure complete clean of RAM/VRAM. I could leave the frame visible though and not clear it but if you try to resize the window it will not resize properly the frame. The other solution would be to copy the frame from the old device/swap chain to the new one. I will review this and include it in the next update.

**Comment by SuRGeoNix** [comment]
Re-check from master if you can and let me know what you think

**Comment by jeroenm2** [comment]
Thanks for your fast reply! Seems logical you want to cleanup the resources. For me both scenarios will work, I do not need the resize on that point. But I understand you want to copy it in the future release, for best best practices.

I just checked master and it looks good, really smooth!
