### ISSUE TITLE
Trouble playing a key frame only mp4 file 

### ISSUE THREAD

**Issue by robertorossinivigilate** [SuRGeoNix/Flyleaf#519]
Hello @SuRGeoNix,
I need to play a mp4 file composed by only key frame. This file is smoothly playable using FFPLAY with FFMPEG; opening it with Flyleaf instead causes the immediate ending of the file.
Dive a little more deep, I notice that CurTime (00:00:14.400) is greater than the Duration (00:00:10.830), but the duration of file is actually 14 seconds.
I attach the sample file here.

https://github.com/user-attachments/assets/e7bec86c-16db-4262-8f7a-083fff32319c

Thanks in advance for your help.

Roberto

**Comment by SuRGeoNix** [comment]
Hi @robertorossinivigilate,

This can be fixed by increasing the 2000 ms in this [line](https://github.com/SuRGeoNix/Flyleaf/blob/v3.8/FlyleafLib/MediaPlayer/Player.Screamers.cs#L446) in Player.Screamer:-

```csharp
if (vDistanceMs > 2000)
```

The 2seconds frame duration is currently to prevent long duration sleeps. This can happen with live streams or even broken timestamps and could freeze the player.

I'm not sure how common is to have 4seconds frame duration. I'm up to discuss this further and possible increase it or exposed with a config.
