### ISSUE TITLE
Updated by NuGet manage packages from v3.7.54 to v3.8.1 - library load now fails

### ISSUE THREAD

**Issue by davsun55** [SuRGeoNix/Flyleaf#525]
I have a working app (Visual Studio; Winforms; C#) successfully playing videos using your libraries.
I just used VSS 'Manage NuGet Packages for solution to upgrade to your latest release v3.8.1
Now when the player is initialised, I get an error 'Loading FFmpeg libaries failed' (see below).
I then downloaded the updated FFmpeg libraries from your Github page and it now seems to be working again.
Apologies for this novice question, but shouldn't they have been updated by the NuGet update? Is there anything else I need to check/do?
Thanks,
David
![Screenshot 2024-11-19 090542](https://github.com/user-attachments/assets/b30497b0-2a23-4834-af2e-5bedb1fdd024)

**Comment by SuRGeoNix** [comment]
[Releases (eg. v8)](https://github.com/SuRGeoNix/Flyleaf/releases/tag/v3.8) will have a detailed changelog and breaking changes.
FFmpeg libs are not included in NuGet because you would have a large size package but mainly because you might want to use your custom compiled libraries (eg. with different license/codecs/formats/etc.).
